Ciekce/Stormphrax

src/tunable.h
=> hand-rescale initial asp window

src/history.h, src/search.cpp
=> don't age history table between searches

src/limit/time.cpp
=> use more time

src/bench.h, src/search.cpp
=> singular extensions

src/search.cpp, src/search.h, src/tunable.h, src/uci.cpp
=> double extensions

src/search.cpp
=> improving in lmp again

src/search.cpp
=> factor history into lmr depth for moveloop pruning

src/search.cpp, src/search.h
=> ensure search threads finish before searching again

src/eval/eval.h
=> scale nnue eval by material on the board

src/search.cpp
=> oversight in conthist updating

src/search.cpp
=> remove weird depth-dependent se limit that I implemented wrong

CMakeLists.txt, src/position/position.h, src/search.cpp
=> check for threefold repetitions in PV nodes

src/search.cpp
=> beta negative extension again

src/history.h
=> 4 ply conthist

src/movegen.h, src/search.cpp, src/search.h, src/tunable.h
=> adjust rfp margin based on parent node's history

src/search.cpp
=> we try again

src/ttable.cpp
=> fix tt mate adjustments

src/search.cpp, src/search.h
=> clear grandchild nodes' killer moves

src/history.h, src/search.cpp
=> fit history scores into 16 bit integers

CMakeLists.txt, src/search.cpp, src/search.h, src/tunable.h
=> verification search for NMP

CMakeLists.txt, src/search.cpp
yellow with gainer bounds, but *easily* passes regression
Bench: 8020371
=> don't store to the TT after a hard timeout

src/eval/eval.h, src/eval/nnue.cpp, src/eval/nnue.h, src/uci.cpp, src/util/simd.h
=> output bucket support + small nnue refactor

CMakeLists.txt, src/tunable.h
loses fairly hard at stc but passed ltc
```
ELO   | -5.36 +- 4.81 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | -2.29 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 9328 W: 2106 L: 2250 D: 4972
```
```
ELO   | 2.43 +- 1.96 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 54984 W: 12706 L: 12322 D: 29956
```
=> do more singular extensions

CMakeLists.txt, Makefile, src/attacks/attacks.h, src/cuckoo.cpp, src/cuckoo.h, src/main.cpp, src/position/position.cpp, src/position/position.h, src/search.cpp
```
ELO   | 5.80 +- 3.68 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.91 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 16288 W: 4021 L: 3749 D: 8518
```
https://chess.swehosting.se/test/4948/
=> detect upcoming repetitions in search

CMakeLists.txt, src/search.cpp
```
ELO   | 4.64 +- 3.19 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.89 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 21328 W: 5155 L: 4870 D: 11303
```
https://chess.swehosting.se/test/5012/
=> return the average of eval and beta from rfp

src/bitboard.h, src/datagen.cpp, src/move.h, src/perft.cpp, src/position/boards.h, src/position/position.cpp, src/position/position.h, src/rays.h, src/search.cpp, src/uci.cpp
=> reject legal moves before making them

src/bench.h, src/main.cpp, src/search.cpp, src/search.h, src/ttable.cpp, src/ttable.h, src/uci.cpp
```
Elo   | 64.06 +- 29.08 (95%)
SPRT  | 32.0+0.32s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 10.00]
Games | N: 554 W: 313 L: 212 D: 29
Penta | [31, 9, 141, 20, 76]
```
https://chess.swehosting.se/test/6183/
=> tt cutoffs

src/movepick.h, src/search.cpp
```
Elo   | 53.02 +- 25.19 (95%)
SPRT  | 30.0+0.30s Threads=1 Hash=32MB
LLR   | 3.03 (-2.94, 2.94) [0.00, 10.00]
Games | N: 700 W: 374 L: 268 D: 58
Penta | [43, 22, 163, 30, 92]
```
https://chess.swehosting.se/test/6186/
=> actually use TT moves

CMakeLists.txt, src/bench.h, src/history.h, src/movepick.h, src/search.cpp, src/search.h, src/tunable.h
```
Elo   | 82.87 +- 31.81 (95%)
SPRT  | 30.0+0.30s Threads=1 Hash=32MB
LLR   | 2.98 (-2.94, 2.94) [0.00, 10.00]
Games | N: 440 W: 244 L: 141 D: 55
Penta | [21, 14, 89, 33, 63]
```
https://chess.swehosting.se/test/6195/
=> basic no-penalty quiet history

src/position/position.cpp, src/position/position.h, src/search.cpp, src/search.h, src/uci.cpp, src/uci.h
```
Elo   | 70.53 +- 20.32 (95%)
LLR   | 3.01 (-2.94, 2.94) [-5.00, 0.00]
Games | N: 764 W: 326 L: 173 D: 265
Penta | [10, 49, 162, 100, 61]
```
https://chess.swehosting.se/test/6229/
also yeet a lot of ancient debug code
=> no rfp in check

src/movepick.h, src/search.cpp, src/search.h, src/tb.cpp, src/tb.h
```
Elo   | 46.52 +- 14.59 (95%)
LLR   | 2.97 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 1112 W: 355 L: 207 D: 550
Penta | [3, 80, 262, 188, 23]
```
https://chess.swehosting.se/test/6258/
=> remove the cursed root move handling

src/movepick.h, src/see.h
```
Elo   | 11.31 +- 7.36 (95%)
SPRT  | 20.0+0.20s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 4302 W: 1153 L: 1013 D: 2136
Penta | [46, 482, 967, 598, 58]
```
https://chess.swehosting.se/test/6299/
=> Good noisy split

src/history.h, src/movepick.h, src/search.cpp, src/search.h
```
Elo   | 15.26 +- 8.90 (95%)
Games | N: 2916 W: 790 L: 662 D: 1464
Penta | [22, 312, 678, 408, 38]
```
https://chess.swehosting.se/test/6440/
=> 1-ply conthist

src/history.h
=> properly coloured conthist piece-to

src/search.cpp
```
Elo   | 5.24 +- 4.77 (95%)
Games | N: 10144 W: 2604 L: 2451 D: 5089
Penta | [73, 1189, 2419, 1294, 97]
```
https://chess.swehosting.se/test/6478/
=> negext if tt score >= beta

src/search.cpp
=> no lmp at root

src/movepick.h, src/search.cpp, src/search.h
```
Elo   | 7.34 +- 5.77 (95%)
Games | N: 6390 W: 1534 L: 1399 D: 3457
Penta | [41, 702, 1580, 825, 47]
```
https://chess.swehosting.se/test/6528/
=> two killers

src/search.cpp, src/ttable.cpp, src/ttable.h, src/tunable.h
```
Elo   | 5.84 +- 5.05 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 8682 W: 2149 L: 2003 D: 4530
Penta | [60, 993, 2088, 1141, 59]
```
https://chess.swehosting.se/test/6542/
=> mostly yoink SF tt replacement scheme

src/movepick.h, src/search.cpp
```
Elo   | 1.46 +- 2.33 (95%)
LLR   | 2.95 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 23530 W: 5552 L: 5453 D: 12525
Penta | [129, 2648, 6144, 2683, 161]
```
https://chess.swehosting.se/test/6770/
=> rewrite movepicker

src/search.cpp
```
Elo   | 8.69 +- 5.09 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 5.00]
Games | N: 5316 W: 1327 L: 1194 D: 2795
Penta | [26, 593, 1314, 672, 53]
```
https://chess.swehosting.se/test/6790/
=> negext if cutnode

src/tunable.h
```
Elo   | 9.72 +- 5.46 (95%)
Games | N: 4542 W: 1113 L: 986 D: 2443
Penta | [21, 503, 1110, 602, 35]
```
https://chess.swehosting.se/test/6949/
=> tighten aspiration windows

src/bench.cpp, src/datagen/datagen.cpp, src/datagen/fen.cpp, src/datagen/marlinformat.cpp, src/eval/nnue/io_impl.h, src/perft.cpp, src/perft.h, src/position/position.cpp, src/position/position.h, src/search.cpp, src/search.h, src/uci.cpp, src/util/cemath.h
```
Elo   | 1.38 +- 2.27 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=16MB
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 23746 W: 5947 L: 5853 D: 11946
Penta | [133, 2538, 6445, 2616, 141]
```
https://chess.swehosting.se/test/9453/
yeet the internal state stack, just copy immutable position objects
=> simplify position handling

CMakeLists.txt, Makefile, src/arch.h, src/util/simd/neon.h
~33% speedup (!!) on an m4 pro
=> neon dotprod support
