Ciekce/Stormphrax

CMakeLists.txt
src/tunable.h

```
ELO   | 12.05 +- 5.55 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=32MB
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 7040 W: 1772 L: 1528 D: 3740
```
```
ELO   | 8.63 +- 4.58 (95%)
SPRT  | 40.0+0.40s Threads=1 Hash=128MB
LLR   | 2.90 (-2.25, 2.89) [0.00, 3.00]
GAMES | N: 9904 W: 2348 L: 2102 D: 5454
```
Bench: 7994769

shortish 20+0.2 spsa

---

src/eval/nnue/input.h
src/eval/nnue/layers.h

3% speedup on clang
as of d3cad26 SP no longer even builds on GCC, so this is irrelevant

remove GCC loop unrolling workaround

---

CMakeLists.txt
src/bench.h
src/movegen.h
src/movepick.h
src/search.cpp
src/search.h

```
Elo   | 284.16 +- 73.73 (95%)
SPRT  | 36.0+0.36s Threads=1 Hash=32MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 184 W: 148 L: 24 D: 12
Penta | [1, 1, 22, 9, 59]
```
https://chess.swehosting.se/test/6129/

order captures first

---

src/core.h
src/movepick.h

```
Elo   | 40.97 +- 22.18 (95%)
SPRT  | 34.0+0.34s Threads=1 Hash=32MB
LLR   | 3.03 (-2.94, 2.94) [0.00, 10.00]
Games | N: 852 W: 425 L: 325 D: 102
Penta | [47, 31, 209, 53, 86]
```
https://chess.swehosting.se/test/6132/

score noisy moves by mvv-lva 

---

src/search.cpp
src/ttable.cpp

```
Elo   | 26.75 +- 12.58 (95%)
SPRT  | 30.0+0.30s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2590 W: 1234 L: 1035 D: 321
Penta | [178, 116, 594, 143, 264]
```
https://chess.swehosting.se/test/6191/

don't overwrite TT moves from the same position when we failed low

---

src/bench.h
src/search.cpp
src/tunable.cpp
src/tunable.h

```
Elo   | 345.15 +- 86.12 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 170 W: 142 L: 13 D: 15
Penta | [0, 1, 12, 14, 58]
```
https://chess.swehosting.se/test/6199/

basic log LMR

---

src/search.cpp

```
Elo   | 79.80 +- 29.19 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 10.00]
Games | N: 412 W: 192 L: 99 D: 121
Penta | [10, 24, 70, 67, 35]
```
https://chess.swehosting.se/test/6202/

lmr more in non-pv nodes

---

src/search.cpp
src/tunable.h

```
Elo   | 16.38 +- 12.32 (95%)
LLR   | 2.98 (-2.94, 2.94) [0.00, 10.00]
Games | N: 1868 W: 614 L: 526 D: 728
Penta | [41, 192, 407, 226, 68]
```
https://chess.swehosting.se/test/6205/

super basic aspiration windows

---

src/limit/time.cpp

```
Elo   | 33.35 +- 18.17 (95%)
LLR   | 2.95 (-2.94, 2.94) [0.00, 10.00]
Games | N: 836 W: 286 L: 206 D: 344
Penta | [18, 74, 169, 124, 33]
```
https://chess.swehosting.se/test/6225/

re-enable soft tm

---

src/search.cpp

```
Elo   | 30.44 +- 17.38 (95%)
LLR   | 3.03 (-2.94, 2.94) [0.00, 10.00]
Games | N: 904 W: 303 L: 224 D: 377
Penta | [13, 93, 179, 136, 31]
```
https://chess.swehosting.se/test/6234/

more nmp reduction at higher depths

---

src/search.cpp

```
Elo   | 40.57 +- 19.80 (95%)
LLR   | 3.05 (-2.94, 2.94) [0.00, 10.00]
Games | N: 628 W: 201 L: 128 D: 299
Penta | [6, 53, 133, 106, 16]
```
https://chess.swehosting.se/test/6242/

don't drop into qsearch in check

---

src/search.cpp

```
Elo   | 33.05 +- 11.77 (95%)
SPRT  | 26.0+0.26s Threads=1 Hash=32MB
LLR   | 3.02 (-2.94, 2.94) [-3.00, 1.00]
Games | N: 1666 W: 492 L: 334 D: 840
Penta | [18, 140, 369, 278, 28]
```
https://chess.swehosting.se/test/6263/

properly detect quiet moves for history

---

src/search.cpp

```
Elo   | 32.77 +- 18.51 (95%)
SPRT  | 24.0+0.24s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 670 W: 196 L: 133 D: 341
Penta | [3, 55, 161, 108, 8]
```
https://chess.swehosting.se/test/6264/

see pruning

---

src/movepick.h
src/search.cpp

```
Elo   | 8.45 +- 7.82 (95%)
SPRT  | 25.0+0.25s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 10.00]
Games | N: 3538 W: 870 L: 784 D: 1884
Penta | [32, 382, 855, 468, 32]
```
https://chess.swehosting.se/test/6265/

forward futility pruning

---

src/history.h
src/movepick.h
src/search.cpp
src/search.h

```
Elo   | 2.85 +- 2.82 (95%)
SPRT  | 24.0+0.24s Threads=1 Hash=32MB
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 27538 W: 6618 L: 6392 D: 14528
Penta | [212, 3253, 6631, 3443, 230]
```
https://chess.swehosting.se/test/6268/
doom emote

replace mvv-lva with mvv + capthist

---

src/history.h
src/movepick.h
src/search.cpp

```
Elo   | 7.41 +- 5.77 (95%)
SPRT  | 22.0+0.22s Threads=1 Hash=32MB
LLR   | 2.95 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6472 W: 1577 L: 1439 D: 3456
Penta | [41, 731, 1561, 855, 48]
```
https://chess.swehosting.se/test/6284/

index butterfly history by whether the from- and to-squares are attacked

---

src/search.cpp
src/search.h

```
Elo   | 15.42 +- 8.96 (95%)
SPRT  | 18.0+0.18s Threads=1 Hash=32MB
LLR   | 3.00 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2864 W: 773 L: 646 D: 1445
Penta | [15, 304, 680, 405, 28]
```
https://chess.swehosting.se/test/6312/

improving in rfp

---

src/search.cpp

```
Elo   | 8.09 +- 6.08 (95%)
SPRT  | 17.0+0.17s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 6060 W: 1539 L: 1398 D: 3123
Penta | [56, 670, 1436, 813, 55]
```
https://chess.swehosting.se/test/6313/

improving in lmp

---

src/search.cpp

```
Elo   | 16.27 +- 8.97 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=32MB
LLR   | 3.02 (-2.94, 2.94) [0.00, 5.00]
Games | N: 2714 W: 703 L: 576 D: 1435
Penta | [17, 270, 669, 371, 30]
```
https://chess.swehosting.se/test/6323/

prefetch TT entries

---

src/bench.h
src/search.cpp
src/search.h

```
Elo   | 9.46 +- 6.62 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=32MB
LLR   | 2.97 (-2.94, 2.94) [0.00, 5.00]
Games | N: 5072 W: 1287 L: 1149 D: 2636
Penta | [45, 569, 1165, 717, 40]
```
https://chess.swehosting.se/test/6325/
in scaling we trust

singular extensions

---

src/search.cpp
src/search.h

```
Elo   | 22.31 +- 10.63 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 1934 W: 517 L: 393 D: 1024
Penta | [11, 193, 441, 305, 17]
```
https://chess.swehosting.se/test/6373/

double extensions

---

src/search.cpp
src/tunable.h

```
Elo   | 4.35 +- 4.09 (95%)
SPRT  | 16.0+0.16s Threads=1 Hash=32MB
LLR   | 2.96 (-2.94, 2.94) [0.00, 5.00]
Games | N: 13412 W: 3336 L: 3168 D: 6908
Penta | [103, 1548, 3271, 1646, 138]
```
https://chess.swehosting.se/test/6377/

triple extensions when score is far below sbeta

---

src/search.cpp
src/tunable.cpp
src/tunable.h

```
Elo   | 7.95 +- 6.17 (95%)
Games | N: 5942 W: 1521 L: 1385 D: 3036
Penta | [40, 670, 1436, 764, 61]
```
https://chess.swehosting.se/test/6433/

reduce bad noisy moves less

---

src/search.cpp

```
Elo   | 15.23 +- 8.80 (95%)
LLR   | 3.00 (-2.25, 2.89) [0.00, 5.00]
Games | N: 2990 W: 812 L: 681 D: 1497
Penta | [27, 301, 715, 418, 34]
```
https://chess.swehosting.se/test/6442/

persist history between searches

---

src/history.h

```
Elo   | 9.65 +- 6.69 (95%)
LLR   | 2.97 (-2.25, 2.89) [0.00, 5.00]
Games | N: 4898 W: 1229 L: 1093 D: 2576
Penta | [36, 545, 1174, 635, 59]
```
https://chess.swehosting.se/test/6448/

2-ply conthist

---

src/search.cpp

```
Elo   | 8.48 +- 6.31 (95%)
Games | N: 5616 W: 1426 L: 1289 D: 2901
Penta | [34, 671, 1294, 742, 67]
```
https://chess.swehosting.se/test/6451/

some kind of history pruning

---

src/search.cpp

```
Elo   | 4.69 +- 4.36 (95%)
Games | N: 12234 W: 3162 L: 2997 D: 6075
Penta | [103, 1447, 2893, 1530, 144]
```
https://chess.swehosting.se/test/6455/

adjust lmr by history

---

src/search.cpp
src/search.h
src/tunable.h

```
Elo   | 0.63 +- 2.35 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 40896 W: 10014 L: 9940 D: 20942
Penta | [288, 4887, 10076, 4857, 340]
```
https://chess.swehosting.se/test/6458/
neutral as expected

stop double counting double extensions

---

src/search.cpp

```
Elo   | 16.04 +- 8.99 (95%)
Games | N: 2710 W: 702 L: 577 D: 1431
Penta | [19, 279, 643, 386, 28]
```
https://chess.swehosting.se/test/6503/

detect upcoming repetitions in search

---

src/search.cpp

```
Elo   | 10.20 +- 7.11 (95%)
Games | N: 4362 W: 1102 L: 974 D: 2286
Penta | [22, 484, 1056, 582, 37]
```
https://chess.swehosting.se/test/6512/

reduce less if improving

---

src/search.cpp

```
Elo   | 3.84 +- 3.74 (95%)
Games | N: 15458 W: 3703 L: 3532 D: 8223
Penta | [109, 1771, 3818, 1902, 129]
```
https://chess.swehosting.se/test/6518/

reduce less if giving check

---

src/movepick.h

```
Elo   | 5.35 +- 4.74 (95%)
Games | N: 9940 W: 2477 L: 2324 D: 5139
Penta | [71, 1164, 2379, 1253, 103]
```
https://chess.swehosting.se/test/6522/

actually skip quiets

---

src/search.cpp

```
Elo   | 3.00 +- 2.42 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 24076 W: 5710 L: 5502 D: 12864
Penta | [176, 2830, 5826, 3022, 184]
```
https://chess.swehosting.se/test/6561/
penta error bars start here

don't drop into qsearch from lmr

---

src/search.cpp
src/search.h

```
Elo   | 5.88 +- 4.31 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 7620 W: 1865 L: 1736 D: 4019
Penta | [53, 872, 1848, 967, 70]
```
https://chess.swehosting.se/test/6578/

switch to a more conventional PVS impl

---

src/search.cpp
src/ttable.cpp
src/ttable.h

```
Elo   | 2.47 +- 2.00 (95%)
Games | N: 35250 W: 8467 L: 8216 D: 18567
Penta | [267, 4174, 8500, 4409, 275]
```
https://chess.swehosting.se/test/6581/

store static eval in the TT

---

src/search.cpp

```
Elo   | 1.07 +- 2.17 (95%)
LLR   | 2.91 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 29872 W: 7172 L: 7080 D: 15620
Penta | [217, 3608, 7213, 3662, 236]
```
https://chess.swehosting.se/test/6593/

don't probe TBs or store to the TT in a singularity search

---

src/limit/time.cpp

```
Elo   | 11.52 +- 6.05 (95%)
Games | N: 3832 W: 968 L: 841 D: 2023
Penta | [25, 410, 927, 521, 33]
```
https://chess.swehosting.se/test/6608/
```
Elo   | 20.83 +- 7.94 (95%)
SPRT  | 70.0+0.70s Threads=1 Hash=32MB
Games | N: 1770 W: 460 L: 354 D: 956
Penta | [3, 149, 478, 249, 6]
```
https://chess.swehosting.se/test/6610/
scalimg

re-enable node tm

---

src/search.cpp
src/search.h

```
Elo   | 17.89 +- 7.87 (95%)
Games | N: 2430 W: 654 L: 529 D: 1247
Penta | [16, 257, 558, 354, 30]
```
https://chess.swehosting.se/test/6632/

cutoff from and store to the TT in qsearch

---

src/search.cpp
src/tunable.h

```
Elo   | 7.93 +- 4.84 (95%)
Games | N: 5786 W: 1443 L: 1311 D: 3032
Penta | [40, 613, 1462, 731, 47]
```
https://chess.swehosting.se/test/6642/

qsearch futility pruning

---

src/search.cpp

```
Elo   | 3.56 +- 2.82 (95%)
Games | N: 17474 W: 4202 L: 4023 D: 9249
Penta | [123, 2046, 4211, 2243, 114]
```
https://chess.swehosting.se/test/6647/

use tt score as eval in qsearch

---

src/history.h
src/search.cpp

```
Elo   | 6.90 +- 4.43 (95%)
LLR   | 2.96 (-2.25, 2.89) [0.00, 5.00]
Games | N: 7048 W: 1739 L: 1599 D: 3710
Penta | [42, 792, 1738, 888, 64]
```
https://chess.swehosting.se/test/6652/

update conthist after unreduced lmr re-search

---

src/movepick.h

```
Elo   | 2.18 +- 2.79 (95%)
LLR   | 2.94 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 17888 W: 4300 L: 4188 D: 9400
Penta | [114, 2154, 4321, 2216, 139]
```
https://chess.swehosting.se/test/6658/

more accidental bad noisy skippage

---

src/search.cpp

```
Elo   | 5.68 +- 3.94 (95%)
Games | N: 8866 W: 2171 L: 2026 D: 4669
Penta | [60, 986, 2211, 1101, 75]
```
https://chess.swehosting.se/test/6659/

use LMR depth for quiet SEE pruning

---

src/search.cpp
src/tunable.h

```
Elo   | 4.14 +- 3.17 (95%)
Games | N: 13832 W: 3313 L: 3148 D: 7371
Penta | [95, 1598, 3378, 1737, 108]
```
https://chess.swehosting.se/test/6685/

extend the entire node if tt bounds were wrong for a cutoff at low depth

---

src/search.cpp

```
Elo   | 2.55 +- 2.99 (95%)
LLR   | 2.90 (-2.25, 2.89) [-3.00, 1.00]
Games | N: 15372 W: 3736 L: 3623 D: 8013
Penta | [91, 1830, 3757, 1891, 117]
```
https://chess.swehosting.se/test/6716/

do no moveloop pruning at root

---

src/movepick.h
src/search.cpp
src/tunable.h

```
Elo   | 0.58 +- 2.37 (95%)
LLR   | -1.45 (-2.25, 2.89) [0.00, 5.00]
Games | N: 24434 W: 5830 L: 5789 D: 12815
Penta | [175, 2891, 6052, 2916, 183]
```
https://chess.swehosting.se/test/6719/
```
Elo   | 4.02 +- 3.03 (95%)
SPRT  | 65.0+0.65s Threads=1 Hash=32MB
Games | N: 12696 W: 2932 L: 2785 D: 6979
Penta | [41, 1372, 3361, 1547, 27]
```
https://chess.swehosting.se/test/6726/
scalimg

successfully p-hack probcut into working

---

src/search.cpp

```
Elo   | 5.27 +- 3.80 (95%)
SPRT  | 6.0+0.06s Threads=1 Hash=32MB
Games | N: 10422 W: 2715 L: 2557 D: 5150
Penta | [115, 1146, 2539, 1288, 123]
```
https://chess.swehosting.se/test/6733/

prefetch the tt in qsearch

---

src/search.cpp

```
Elo   | 3.25 +- 2.59 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 20648 W: 4969 L: 4776 D: 10903
Penta | [127, 2439, 5046, 2538, 174]
```
https://chess.swehosting.se/test/6804/

use lmr depth in depth condition for history pruning

---

src/search.cpp

```
Elo   | 5.44 +- 3.83 (95%)
LLR   | 2.93 (-2.25, 2.89) [0.00, 5.00]
Games | N: 9710 W: 2358 L: 2206 D: 5146
Penta | [78, 1105, 2340, 1251, 81]
```

bigger history bonus if static eval fails low

---

src/search.cpp

```
Elo   | 2.79 +- 2.26 (95%)
Games | N: 27306 W: 6654 L: 6435 D: 14217
Penta | [205, 3176, 6688, 3363, 221]
```
https://chess.swehosting.se/test/6843/

don't do nmp where the tt indicates it would fail

---

src/search.cpp
src/tunable.h

```
Elo   | 3.15 +- 2.54 (95%)
Games | N: 21036 W: 4986 L: 4795 D: 11255
Penta | [139, 2428, 5188, 2629, 134]
```
https://chess.swehosting.se/test/6900/

reduce depth on aspiration window failhighs

---

src/movepick.h
src/search.cpp

```
Elo   | 2.53 +- 2.05 (95%)
Games | N: 32288 W: 7659 L: 7424 D: 17205
Penta | [203, 3781, 7933, 4032, 195]
```
https://chess.swehosting.se/test/6917/

search tt moves in qsearch

---

src/search.cpp

```
Elo   | 4.10 +- 3.15 (95%)
Games | N: 13884 W: 3392 L: 3228 D: 7264
Penta | [80, 1625, 3404, 1717, 116]
```
https://chess.swehosting.se/test/6925/

Nmp eval reduction

---

src/search.cpp

```
Elo   | 3.28 +- 2.61 (95%)
LLR   | 2.94 (-2.25, 2.89) [0.00, 5.00]
Games | N: 19592 W: 4664 L: 4479 D: 10449
Penta | [108, 2275, 4857, 2436, 120]
```
https://chess.swehosting.se/test/6932/

reduce more in nmp if improving

---

src/search.cpp

```
Elo   | 3.10 +- 2.48 (95%)
LLR   | 2.95 (-2.25, 2.89) [0.00, 5.00]
Games | N: 21768 W: 5237 L: 5043 D: 11488
Penta | [121, 2523, 5437, 2647, 156]
```
https://chess.swehosting.se/test/6952/

sf dodeeper/shallowersearch

---

src/tunable.h

STC of slightly different values (wrong probcut margin, and un-hand-tuned sbeta)
```
Elo   | 14.25 +- 6.73 (95%)
Games | N: 2928 W: 729 L: 609 D: 1590
Penta | [17, 292, 728, 408, 19]
```
https://chess.swehosting.se/test/7017/
```
Elo   | 17.67 +- 7.36 (95%)
SPRT  | 65.0+0.65s Threads=1 Hash=32MB
Games | N: 2184 W: 548 L: 437 D: 1199
Penta | [6, 205, 557, 320, 4]
```
https://chess.swehosting.se/test/7018/
tune: https://chess.swehosting.se/tune/6969/ (nice)

spsa 6250 iterations

---

src/position/position.cpp
src/position/position.h
src/see.h
src/uci.cpp

```
Elo   | 5.19 +- 3.04 (95%)
SPRT  | 8.0+0.08s Threads=1 Hash=16MB
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 14520 W: 3635 L: 3418 D: 7467
Penta | [82, 1641, 3624, 1804, 109]
```
https://chess.swehosting.se/test/10554/

Handle pinned pieces in SEE

---

src/movepick.h

```
Elo   | 1.37 +- 1.05 (95%)
SPRT  | 4.0+0.04s Threads=1 Hash=16MB
LLR   | 2.94 (-2.25, 2.89) [0.00, 3.00]
Games | N: 151268 W: 39712 L: 39115 D: 72441
Penta | [2370, 17455, 35471, 17884, 2454]
```
https://chess.swehosting.se/test/11188/
`findBest` is now branchless and gets autovectorized pretty well.

faster movepicker
